version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: owncloud_server_1
      APP_PORT: 8080

  server:
    image: owncloud/server:10.15.3
    container_name: owncloud_server_1
    restart: on-failure
    environment:
      - OWNCLOUD_DOMAIN=${APP_DOMAIN}:8080
      - OWNCLOUD_TRUSTED_DOMAINS=${APP_DOMAIN}
      - OWNCLOUD_DB_TYPE=sqlite
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin
      - OWNCLOUD_LOG_LEVEL=2
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${APP_DATA_DIR}/files:/mnt/data
      - ${APP_DATA_DIR}/config:/var/www/owncloud/config
